### ISSUE TITLE
Cache Time is configured in seconds while nextTimestamp returns deciseconds

### ISSUE THREAD

**Issue by yvesf** [mihaicostin/hibernate-l2-memcached#12]
In class MemcachedCache the two methods:
```java
    public long nextTimestamp() {
        return System.currentTimeMillis() / 100;
    }

    public int getTimeout() {
        return cacheTimeSeconds;
    }
```

return inconsistent time units. This creates wrong calculations, see hibernates UpdateTiemstampsCache#preInvalidate:
```java
		final Long ts = region.nextTimestamp() + region.getTimeout();
```
adding seconds to deciseconds.

I guess the `/ 100` should just be `/ 1000` ?

See this for reference: https://github.com/hibernate/hibernate-orm/blob/master/hibernate-ehcache/src/main/java/org/hibernate/cache/ehcache/internal/regions/EhcacheDataRegion.java#L61

**Comment by mihaicostin** [comment]
yep, you do have a point regarding that inconsistency. 

I'm thinking that maybe I should make both methods return ms, i.e. 
```
public long nextTimestamp() {
        return System.currentTimeMillis();
    }

    public int getTimeout() {
        return cacheTimeSeconds * 1000;
    }
```
I could also use the more elaborate approach with the Timestamper like ehcache, but I don't think I see the benefit in that. 

Also.. it might be a good idea to use a separate property for the region timeout (or lock timeout, as it's being used) instead of reusing the cache timeout.

**Comment by mihaicostin** [comment]
handled by cache property `hibernate.memcached.cacheLockTimeout`
